### ISSUE TITLE
Some search results with counts cannot be deserialized when the result has no rows

### ISSUE THREAD

**Issue by jnhagelberg** [IBM/cloudant-java-sdk#342] opened 2022-09-15 19:16 UTC
Example:

In our tests, a particular cloudant query produces the following result:
```
{"total_rows":0,"bookmark":"g2o","rows":[],"counts":{"omrs_entity.omrs_type":0.0}}
```

This response  cannot be deserialized to `SearchResult`.  The deserialization fails as follow:
```
Caused by: com.ibm.cloud.sdk.core.service.exception.InvalidServiceResponseException: Error processing the http response
	at com.ibm.cloud.sdk.core.service.BaseService.processServiceCall(BaseService.java:524)
	at com.ibm.cloud.sdk.core.service.BaseService$IBMCloudSDKServiceCall.execute(BaseService.java:582)
	at com.ibm.catalog.unified.dao.cloudant.IBMSDKCloudantSearch.querySearchResultAndLog(IBMSDKCloudantSearch.java:194)
	... 50 more
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 78 path $.counts.
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:963)
	at com.ibm.cloud.sdk.core.util.ResponseUtils.getValue(ResponseUtils.java:149)
	at com.ibm.cloud.sdk.core.util.ResponseConverterUtils$6.convert(ResponseConverterUtils.java:137)
	at com.ibm.cloud.sdk.core.service.BaseService.processServiceCall(BaseService.java:522)
	... 52 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 78 path $.counts.
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 56 more
```

The easiest way to reproduce this is to write a junit test to deserialize the above snippet.  The request body query for the query we sent was (for whatever it's worth):
```
{
  "db": "dls_v2_cc33d69d-47f0-49c3-82bc-d6418f5485ff_assets",
  "ddoc": "search_omrs_entity",
  "index": "search_omrs_entity",
  "query": "(asset.asset_state: \"available\" AND  ( asset.mode:[ 0 TO 8 ] OR asset.memberIds: \"iam-ServiceId-0cf5b102-17b3-4638-95df-309a2a443137\" OR asset.owner_id: \"iam-ServiceId-0cf5b102-17b3-4638-95df-309a2a443137\" )  AND (asset.created_at:[ \"2022-09-15T18:20:59Z\" TO * ]))",
  "includeDocs": true,
  "limit": 0,
  "counts": [
    "omrs_entity.omrs_type"
  ]
}
```

The query returned no rows in this use case.  It is interesting that in the case where total rows != 0, the result can be properly deserialized:
```
{"total_rows":12,"bookmark":"g2o","rows":[],"counts":{"omrs_entity.omrs_type":{"Connection":1.0,"Database":2.0,"DeployedDatabaseSchema":1.0,"Endpoint":1.0,"RelationalColumn":1.0,"RelationalColumnType":1.0,"RelationalDBSchemaType":1.0,"RelationalTable":2.0,"RelationalTableType":2.0}}}
```

**Comment by jnhagelberg** [comment] 2022-09-16 01:51
FYI - we were able to work around this using code similar to the following.  We basically deserialize the counts separately:
```
 private SearchResult deserializeSearchResult(JsonObject obj) {

        JsonElement countsToDeserialize = obj.get("counts");
        obj.remove("counts");
        SearchResult responseWithNoCounts = GsonSingleton.getGson().fromJson(obj, SearchResult.class);
        Map<String, Map<String, Long>> counts = deserializeCounts(countsToDeserialize);
        responseWithNoCounts.setCounts(counts);
        return responseWithNoCounts;
    }

    private Map<String, Map<String,Long>> deserializeCounts(JsonElement countsToDeserialize) {

        Map<String, Map<String,Long>> counts = null;
        if (countsToDeserialize != null && countsToDeserialize.isJsonObject()) {
            JsonObject countsObj = countsToDeserialize.getAsJsonObject();
            counts = new HashMap<>(countsObj.size());
            for(Map.Entry<String, JsonElement> element : countsObj.entrySet()) {
                String key = element.getKey();
                JsonElement value = element.getValue();
                if (value.isJsonObject()) {
                    Map<String, Long> valueMap = GSON.fromJson(value, LONG_MAP_TYPE);
                    counts.put(key, valueMap);
                }
                else {
                    counts.put(key, Collections.emptyMap());
                }
            }
        }
        return counts;
    }
```

**Comment by ricellis** [comment] 2022-09-16 09:14
Duplicate of #211

**Closed by ricellis** 2022-09-16 09:14 UTC
Labels: duplicate

**Comment by ricellis** [comment] 2023-09-22 08:53
There is a server-side correction for this issue from Cloudant version [8442](https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-classic-release-notes#Cloudant-sep1423).
